03-16 16:49:46 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.panic(MVStore.java:368)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:351)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2782)
	at org.h2.mvstore.db.MVTableEngine$Store.<init>(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:98)
	at org.h2.engine.Database.getPageStore(Database.java:2389)
	at org.h2.engine.Database.open(Database.java:669)
	at org.h2.engine.Database.openDatabase(Database.java:266)
	at org.h2.engine.Database.<init>(Database.java:260)
	at org.h2.engine.Engine.openSession(Engine.java:60)
	at org.h2.engine.Engine.openSession(Engine.java:167)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:145)
	at org.h2.engine.Engine.createSession(Engine.java:128)
	at org.h2.engine.Engine.createSession(Engine.java:26)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:347)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:108)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:92)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.getDBConnection(H2ConnectionManager.java:402)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.<init>(H2ConnectionManager.java:64)
	at net.ages.alwb.utils.core.datastores.db.factory.DbConnectionFactory.getH2Manager(DbConnectionFactory.java:32)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.<init>(InternalDbManager.java:116)
	at ioc.liturgical.ws.app.ServiceProvider.main(ServiceProvider.java:274)
	at ioc.liturgical.ws.ServiceProviderTest.setUpBeforeClass(ServiceProviderTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 45 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:337)
	... 40 more
03-16 16:50:03 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.panic(MVStore.java:368)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:351)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2782)
	at org.h2.mvstore.db.MVTableEngine$Store.<init>(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:98)
	at org.h2.engine.Database.getPageStore(Database.java:2389)
	at org.h2.engine.Database.open(Database.java:669)
	at org.h2.engine.Database.openDatabase(Database.java:266)
	at org.h2.engine.Database.<init>(Database.java:260)
	at org.h2.engine.Engine.openSession(Engine.java:60)
	at org.h2.engine.Engine.openSession(Engine.java:167)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:145)
	at org.h2.engine.Engine.createSession(Engine.java:128)
	at org.h2.engine.Engine.createSession(Engine.java:26)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:347)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:108)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:92)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.getDBConnection(H2ConnectionManager.java:402)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.<init>(H2ConnectionManager.java:64)
	at net.ages.alwb.utils.core.datastores.db.factory.DbConnectionFactory.getH2Manager(DbConnectionFactory.java:32)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.<init>(InternalDbManager.java:116)
	at ioc.liturgical.ws.app.ServiceProvider.main(ServiceProvider.java:274)
	at ioc.liturgical.ws.ServiceProviderTest.setUpBeforeClass(ServiceProviderTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 45 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:337)
	... 40 more
03-17 15:18:02 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.panic(MVStore.java:368)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:351)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2782)
	at org.h2.mvstore.db.MVTableEngine$Store.<init>(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:98)
	at org.h2.engine.Database.getPageStore(Database.java:2389)
	at org.h2.engine.Database.open(Database.java:669)
	at org.h2.engine.Database.openDatabase(Database.java:266)
	at org.h2.engine.Database.<init>(Database.java:260)
	at org.h2.engine.Engine.openSession(Engine.java:60)
	at org.h2.engine.Engine.openSession(Engine.java:167)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:145)
	at org.h2.engine.Engine.createSession(Engine.java:128)
	at org.h2.engine.Engine.createSession(Engine.java:26)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:347)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:108)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:92)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.getDBConnection(H2ConnectionManager.java:402)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.<init>(H2ConnectionManager.java:64)
	at net.ages.alwb.utils.core.datastores.db.factory.DbConnectionFactory.getH2Manager(DbConnectionFactory.java:32)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.<init>(InternalDbManager.java:116)
	at ioc.liturgical.ws.app.ServiceProvider.main(ServiceProvider.java:274)
	at ioc.liturgical.ws.ServiceProviderTest.setUpBeforeClass(ServiceProviderTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.infinitest.testrunner.JUnit4Runner.runJUnitTest(JUnit4Runner.java:97)
	at org.infinitest.testrunner.JUnit4Runner.runTest(JUnit4Runner.java:63)
	at org.infinitest.testrunner.TestRunnerProcess.runTest(TestRunnerProcess.java:70)
	at org.infinitest.testrunner.TestRunnerProcess.writeTestResultToOutputStream(TestRunnerProcess.java:112)
	at org.infinitest.testrunner.TestRunnerProcess.main(TestRunnerProcess.java:89)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 46 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:337)
	... 41 more
03-17 15:18:04 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.panic(MVStore.java:368)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:351)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2782)
	at org.h2.mvstore.db.MVTableEngine$Store.<init>(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:98)
	at org.h2.engine.Database.getPageStore(Database.java:2389)
	at org.h2.engine.Database.open(Database.java:669)
	at org.h2.engine.Database.openDatabase(Database.java:266)
	at org.h2.engine.Database.<init>(Database.java:260)
	at org.h2.engine.Engine.openSession(Engine.java:60)
	at org.h2.engine.Engine.openSession(Engine.java:167)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:145)
	at org.h2.engine.Engine.createSession(Engine.java:128)
	at org.h2.engine.Engine.createSession(Engine.java:26)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:347)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:108)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:92)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.getDBConnection(H2ConnectionManager.java:402)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.<init>(H2ConnectionManager.java:64)
	at net.ages.alwb.utils.core.datastores.db.factory.DbConnectionFactory.getH2Manager(DbConnectionFactory.java:32)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.<init>(InternalDbManager.java:116)
	at ioc.liturgical.ws.app.ServiceProvider.main(ServiceProvider.java:274)
	at ioc.liturgical.ws.TestPathDomains.setUpBeforeClass(TestPathDomains.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.infinitest.testrunner.JUnit4Runner.runJUnitTest(JUnit4Runner.java:97)
	at org.infinitest.testrunner.JUnit4Runner.runTest(JUnit4Runner.java:63)
	at org.infinitest.testrunner.TestRunnerProcess.runTest(TestRunnerProcess.java:70)
	at org.infinitest.testrunner.TestRunnerProcess.writeTestResultToOutputStream(TestRunnerProcess.java:112)
	at org.infinitest.testrunner.TestRunnerProcess.main(TestRunnerProcess.java:89)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 46 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:337)
	... 41 more
03-17 15:18:05 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.panic(MVStore.java:368)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:351)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2782)
	at org.h2.mvstore.db.MVTableEngine$Store.<init>(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:98)
	at org.h2.engine.Database.getPageStore(Database.java:2389)
	at org.h2.engine.Database.open(Database.java:669)
	at org.h2.engine.Database.openDatabase(Database.java:266)
	at org.h2.engine.Database.<init>(Database.java:260)
	at org.h2.engine.Engine.openSession(Engine.java:60)
	at org.h2.engine.Engine.openSession(Engine.java:167)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:145)
	at org.h2.engine.Engine.createSession(Engine.java:128)
	at org.h2.engine.Engine.createSession(Engine.java:26)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:347)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:108)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:92)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.getDBConnection(H2ConnectionManager.java:402)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.<init>(H2ConnectionManager.java:64)
	at net.ages.alwb.utils.core.datastores.db.factory.DbConnectionFactory.getH2Manager(DbConnectionFactory.java:32)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.<init>(InternalDbManager.java:116)
	at ioc.liturgical.ws.app.ServiceProvider.main(ServiceProvider.java:274)
	at ioc.liturgical.ws.TestPathAdminDbUsers.setUpBeforeClass(TestPathAdminDbUsers.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.infinitest.testrunner.JUnit4Runner.runJUnitTest(JUnit4Runner.java:97)
	at org.infinitest.testrunner.JUnit4Runner.runTest(JUnit4Runner.java:63)
	at org.infinitest.testrunner.TestRunnerProcess.runTest(TestRunnerProcess.java:70)
	at org.infinitest.testrunner.TestRunnerProcess.writeTestResultToOutputStream(TestRunnerProcess.java:112)
	at org.infinitest.testrunner.TestRunnerProcess.main(TestRunnerProcess.java:89)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 46 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:337)
	... 41 more
03-17 15:18:05 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.panic(MVStore.java:368)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:351)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2782)
	at org.h2.mvstore.db.MVTableEngine$Store.<init>(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:98)
	at org.h2.engine.Database.getPageStore(Database.java:2389)
	at org.h2.engine.Database.open(Database.java:669)
	at org.h2.engine.Database.openDatabase(Database.java:266)
	at org.h2.engine.Database.<init>(Database.java:260)
	at org.h2.engine.Engine.openSession(Engine.java:60)
	at org.h2.engine.Engine.openSession(Engine.java:167)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:145)
	at org.h2.engine.Engine.createSession(Engine.java:128)
	at org.h2.engine.Engine.createSession(Engine.java:26)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:347)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:108)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:92)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.getDBConnection(H2ConnectionManager.java:402)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.<init>(H2ConnectionManager.java:64)
	at net.ages.alwb.utils.core.datastores.db.factory.DbConnectionFactory.getH2Manager(DbConnectionFactory.java:32)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.<init>(InternalDbManager.java:116)
	at ioc.liturgical.ws.app.ServiceProvider.main(ServiceProvider.java:274)
	at ioc.liturgical.ws.TestPathAdminAdmins.setUpBeforeClass(TestPathAdminAdmins.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.infinitest.testrunner.JUnit4Runner.runJUnitTest(JUnit4Runner.java:97)
	at org.infinitest.testrunner.JUnit4Runner.runTest(JUnit4Runner.java:63)
	at org.infinitest.testrunner.TestRunnerProcess.runTest(TestRunnerProcess.java:70)
	at org.infinitest.testrunner.TestRunnerProcess.writeTestResultToOutputStream(TestRunnerProcess.java:112)
	at org.infinitest.testrunner.TestRunnerProcess.main(TestRunnerProcess.java:89)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 46 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:337)
	... 41 more
03-17 15:20:37 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.panic(MVStore.java:368)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:351)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2782)
	at org.h2.mvstore.db.MVTableEngine$Store.<init>(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:98)
	at org.h2.engine.Database.getPageStore(Database.java:2389)
	at org.h2.engine.Database.open(Database.java:669)
	at org.h2.engine.Database.openDatabase(Database.java:266)
	at org.h2.engine.Database.<init>(Database.java:260)
	at org.h2.engine.Engine.openSession(Engine.java:60)
	at org.h2.engine.Engine.openSession(Engine.java:167)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:145)
	at org.h2.engine.Engine.createSession(Engine.java:128)
	at org.h2.engine.Engine.createSession(Engine.java:26)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:347)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:108)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:92)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.getDBConnection(H2ConnectionManager.java:402)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.<init>(H2ConnectionManager.java:64)
	at net.ages.alwb.utils.core.datastores.db.factory.DbConnectionFactory.getH2Manager(DbConnectionFactory.java:32)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.<init>(InternalDbManager.java:116)
	at ioc.liturgical.ws.app.ServiceProvider.main(ServiceProvider.java:274)
	at ioc.liturgical.ws.ServiceProviderTest.setUpBeforeClass(ServiceProviderTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.infinitest.testrunner.JUnit4Runner.runJUnitTest(JUnit4Runner.java:97)
	at org.infinitest.testrunner.JUnit4Runner.runTest(JUnit4Runner.java:63)
	at org.infinitest.testrunner.TestRunnerProcess.runTest(TestRunnerProcess.java:70)
	at org.infinitest.testrunner.TestRunnerProcess.writeTestResultToOutputStream(TestRunnerProcess.java:112)
	at org.infinitest.testrunner.TestRunnerProcess.main(TestRunnerProcess.java:89)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 46 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:337)
	... 41 more
03-17 15:20:39 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.panic(MVStore.java:368)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:351)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2782)
	at org.h2.mvstore.db.MVTableEngine$Store.<init>(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:98)
	at org.h2.engine.Database.getPageStore(Database.java:2389)
	at org.h2.engine.Database.open(Database.java:669)
	at org.h2.engine.Database.openDatabase(Database.java:266)
	at org.h2.engine.Database.<init>(Database.java:260)
	at org.h2.engine.Engine.openSession(Engine.java:60)
	at org.h2.engine.Engine.openSession(Engine.java:167)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:145)
	at org.h2.engine.Engine.createSession(Engine.java:128)
	at org.h2.engine.Engine.createSession(Engine.java:26)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:347)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:108)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:92)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.getDBConnection(H2ConnectionManager.java:402)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.<init>(H2ConnectionManager.java:64)
	at net.ages.alwb.utils.core.datastores.db.factory.DbConnectionFactory.getH2Manager(DbConnectionFactory.java:32)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.<init>(InternalDbManager.java:116)
	at ioc.liturgical.ws.app.ServiceProvider.main(ServiceProvider.java:274)
	at ioc.liturgical.ws.TestPathDomains.setUpBeforeClass(TestPathDomains.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.infinitest.testrunner.JUnit4Runner.runJUnitTest(JUnit4Runner.java:97)
	at org.infinitest.testrunner.JUnit4Runner.runTest(JUnit4Runner.java:63)
	at org.infinitest.testrunner.TestRunnerProcess.runTest(TestRunnerProcess.java:70)
	at org.infinitest.testrunner.TestRunnerProcess.writeTestResultToOutputStream(TestRunnerProcess.java:112)
	at org.infinitest.testrunner.TestRunnerProcess.main(TestRunnerProcess.java:89)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 46 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:337)
	... 41 more
03-17 15:20:40 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.panic(MVStore.java:368)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:351)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2782)
	at org.h2.mvstore.db.MVTableEngine$Store.<init>(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:98)
	at org.h2.engine.Database.getPageStore(Database.java:2389)
	at org.h2.engine.Database.open(Database.java:669)
	at org.h2.engine.Database.openDatabase(Database.java:266)
	at org.h2.engine.Database.<init>(Database.java:260)
	at org.h2.engine.Engine.openSession(Engine.java:60)
	at org.h2.engine.Engine.openSession(Engine.java:167)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:145)
	at org.h2.engine.Engine.createSession(Engine.java:128)
	at org.h2.engine.Engine.createSession(Engine.java:26)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:347)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:108)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:92)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.getDBConnection(H2ConnectionManager.java:402)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.<init>(H2ConnectionManager.java:64)
	at net.ages.alwb.utils.core.datastores.db.factory.DbConnectionFactory.getH2Manager(DbConnectionFactory.java:32)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.<init>(InternalDbManager.java:116)
	at ioc.liturgical.ws.app.ServiceProvider.main(ServiceProvider.java:274)
	at ioc.liturgical.ws.TestPathAdminDbUsers.setUpBeforeClass(TestPathAdminDbUsers.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.infinitest.testrunner.JUnit4Runner.runJUnitTest(JUnit4Runner.java:97)
	at org.infinitest.testrunner.JUnit4Runner.runTest(JUnit4Runner.java:63)
	at org.infinitest.testrunner.TestRunnerProcess.runTest(TestRunnerProcess.java:70)
	at org.infinitest.testrunner.TestRunnerProcess.writeTestResultToOutputStream(TestRunnerProcess.java:112)
	at org.infinitest.testrunner.TestRunnerProcess.main(TestRunnerProcess.java:89)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 46 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:337)
	... 41 more
03-17 15:20:40 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.panic(MVStore.java:368)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:351)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2782)
	at org.h2.mvstore.db.MVTableEngine$Store.<init>(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:98)
	at org.h2.engine.Database.getPageStore(Database.java:2389)
	at org.h2.engine.Database.open(Database.java:669)
	at org.h2.engine.Database.openDatabase(Database.java:266)
	at org.h2.engine.Database.<init>(Database.java:260)
	at org.h2.engine.Engine.openSession(Engine.java:60)
	at org.h2.engine.Engine.openSession(Engine.java:167)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:145)
	at org.h2.engine.Engine.createSession(Engine.java:128)
	at org.h2.engine.Engine.createSession(Engine.java:26)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:347)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:108)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:92)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.getDBConnection(H2ConnectionManager.java:402)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.<init>(H2ConnectionManager.java:64)
	at net.ages.alwb.utils.core.datastores.db.factory.DbConnectionFactory.getH2Manager(DbConnectionFactory.java:32)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.<init>(InternalDbManager.java:116)
	at ioc.liturgical.ws.app.ServiceProvider.main(ServiceProvider.java:274)
	at ioc.liturgical.ws.TestPathAdminAdmins.setUpBeforeClass(TestPathAdminAdmins.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.infinitest.testrunner.JUnit4Runner.runJUnitTest(JUnit4Runner.java:97)
	at org.infinitest.testrunner.JUnit4Runner.runTest(JUnit4Runner.java:63)
	at org.infinitest.testrunner.TestRunnerProcess.runTest(TestRunnerProcess.java:70)
	at org.infinitest.testrunner.TestRunnerProcess.writeTestResultToOutputStream(TestRunnerProcess.java:112)
	at org.infinitest.testrunner.TestRunnerProcess.main(TestRunnerProcess.java:89)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 46 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/git/ocmc/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:337)
	... 41 more
03-28 13:42:42 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/Git/ocmc-translation-projects/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.panic(MVStore.java:368)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:351)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2782)
	at org.h2.mvstore.db.MVTableEngine$Store.<init>(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:98)
	at org.h2.engine.Database.getPageStore(Database.java:2389)
	at org.h2.engine.Database.open(Database.java:669)
	at org.h2.engine.Database.openDatabase(Database.java:266)
	at org.h2.engine.Database.<init>(Database.java:260)
	at org.h2.engine.Engine.openSession(Engine.java:60)
	at org.h2.engine.Engine.openSession(Engine.java:167)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:145)
	at org.h2.engine.Engine.createSession(Engine.java:128)
	at org.h2.engine.Engine.createSession(Engine.java:26)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:347)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:108)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:92)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.getDBConnection(H2ConnectionManager.java:402)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.<init>(H2ConnectionManager.java:64)
	at net.ages.alwb.utils.core.datastores.db.factory.DbConnectionFactory.getH2Manager(DbConnectionFactory.java:32)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.<init>(InternalDbManager.java:115)
	at ioc.liturgical.ws.app.ServiceProvider.main(ServiceProvider.java:274)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/Git/ocmc-translation-projects/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 28 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/Git/ocmc-translation-projects/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:337)
	... 23 more
03-29 13:01:17 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/Git/ocmc-translation-projects/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.panic(MVStore.java:368)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:351)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2782)
	at org.h2.mvstore.db.MVTableEngine$Store.<init>(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:98)
	at org.h2.engine.Database.getPageStore(Database.java:2389)
	at org.h2.engine.Database.open(Database.java:669)
	at org.h2.engine.Database.openDatabase(Database.java:266)
	at org.h2.engine.Database.<init>(Database.java:260)
	at org.h2.engine.Engine.openSession(Engine.java:60)
	at org.h2.engine.Engine.openSession(Engine.java:167)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:145)
	at org.h2.engine.Engine.createSession(Engine.java:128)
	at org.h2.engine.Engine.createSession(Engine.java:26)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:347)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:108)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:92)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.getDBConnection(H2ConnectionManager.java:402)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.<init>(H2ConnectionManager.java:64)
	at net.ages.alwb.utils.core.datastores.db.factory.DbConnectionFactory.getH2Manager(DbConnectionFactory.java:32)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.<init>(InternalDbManager.java:115)
	at ioc.liturgical.ws.app.ServiceProvider.main(ServiceProvider.java:274)
	at ioc.liturgical.ws.ServiceProviderTest.setUpBeforeClass(ServiceProviderTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/Git/ocmc-translation-projects/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 45 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/Users/mac002/Git/ocmc-translation-projects/ioc-liturgical-ws/ioc-liturgical-db.mv.db [1.4.187/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:337)
	... 40 more
03-30 10:05:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-187]
03-31 12:31:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.message.DbException.toSQLException(DbException.java:268)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:352)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:124)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJson(H2ConnectionManager.java:380)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJsonWhereEqual(H2ConnectionManager.java:344)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getForId(InternalDbManager.java:265)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.existsUser(InternalDbManager.java:777)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getUserStatus(InternalDbManager.java:1582)
	at ioc.liturgical.ws.app.ServiceProvider.lambda$0(ServiceProvider.java:324)
	at spark.FilterImpl$1.handle(FilterImpl.java:62)
	at spark.http.matching.BeforeFilters.execute(BeforeFilters.java:48)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcStatement.checkClosed(JdbcStatement.java:986)
	at org.h2.jdbc.JdbcPreparedStatement.checkClosed(JdbcPreparedStatement.java:1620)
	at org.h2.jdbc.JdbcStatement.checkClosed(JdbcStatement.java:959)
	at org.h2.jdbc.JdbcResultSet.checkClosed(JdbcResultSet.java:3177)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:121)
	... 24 more
03-31 14:12:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.message.DbException.toSQLException(DbException.java:268)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:352)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:124)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJson(H2ConnectionManager.java:380)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJsonWhereEqual(H2ConnectionManager.java:344)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getForId(InternalDbManager.java:265)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.existsUser(InternalDbManager.java:777)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getUserStatus(InternalDbManager.java:1582)
	at ioc.liturgical.ws.app.ServiceProvider.lambda$0(ServiceProvider.java:324)
	at spark.FilterImpl$1.handle(FilterImpl.java:62)
	at spark.http.matching.BeforeFilters.execute(BeforeFilters.java:48)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcResultSet.nextRow(JdbcResultSet.java:3233)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:122)
	... 24 more
04-02 15:11:17 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.message.DbException.toSQLException(DbException.java:268)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:352)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:124)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJson(H2ConnectionManager.java:380)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJsonWhereEqual(H2ConnectionManager.java:344)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getForId(InternalDbManager.java:265)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.existsUser(InternalDbManager.java:777)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getUserStatus(InternalDbManager.java:1582)
	at ioc.liturgical.ws.app.ServiceProvider.lambda$0(ServiceProvider.java:324)
	at spark.FilterImpl$1.handle(FilterImpl.java:62)
	at spark.http.matching.BeforeFilters.execute(BeforeFilters.java:48)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcStatement.checkClosed(JdbcStatement.java:986)
	at org.h2.jdbc.JdbcPreparedStatement.checkClosed(JdbcPreparedStatement.java:1620)
	at org.h2.jdbc.JdbcStatement.checkClosed(JdbcStatement.java:959)
	at org.h2.jdbc.JdbcResultSet.checkClosed(JdbcResultSet.java:3177)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:121)
	... 24 more
04-07 11:23:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-187]
04-09 07:57:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.message.DbException.toSQLException(DbException.java:268)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:352)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:124)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJson(H2ConnectionManager.java:380)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJsonWhereEqual(H2ConnectionManager.java:344)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getForId(InternalDbManager.java:266)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.existsUser(InternalDbManager.java:775)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getUserStatus(InternalDbManager.java:1616)
	at ioc.liturgical.ws.app.ServiceProvider.lambda$0(ServiceProvider.java:324)
	at spark.FilterImpl$1.handle(FilterImpl.java:62)
	at spark.http.matching.BeforeFilters.execute(BeforeFilters.java:48)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcResultSet.nextRow(JdbcResultSet.java:3231)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:122)
	... 24 more
04-10 08:16:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.message.DbException.toSQLException(DbException.java:268)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:352)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:124)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJson(H2ConnectionManager.java:380)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJsonWhereEqual(H2ConnectionManager.java:344)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getForId(InternalDbManager.java:266)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.existsUser(InternalDbManager.java:775)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getUserStatus(InternalDbManager.java:1616)
	at ioc.liturgical.ws.app.ServiceProvider.lambda$0(ServiceProvider.java:324)
	at spark.FilterImpl$1.handle(FilterImpl.java:62)
	at spark.http.matching.BeforeFilters.execute(BeforeFilters.java:48)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcStatement.checkClosed(JdbcStatement.java:986)
	at org.h2.jdbc.JdbcPreparedStatement.checkClosed(JdbcPreparedStatement.java:1620)
	at org.h2.jdbc.JdbcStatement.checkClosed(JdbcStatement.java:959)
	at org.h2.jdbc.JdbcResultSet.checkClosed(JdbcResultSet.java:3177)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:121)
	... 24 more
04-11 11:03:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.message.DbException.toSQLException(DbException.java:268)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:352)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:124)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJson(H2ConnectionManager.java:380)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJsonWhereEqual(H2ConnectionManager.java:344)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getForId(InternalDbManager.java:266)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.existsUser(InternalDbManager.java:775)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getUserStatus(InternalDbManager.java:1616)
	at ioc.liturgical.ws.app.ServiceProvider.lambda$0(ServiceProvider.java:324)
	at spark.FilterImpl$1.handle(FilterImpl.java:62)
	at spark.http.matching.BeforeFilters.execute(BeforeFilters.java:48)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcResultSet.nextRow(JdbcResultSet.java:3233)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:122)
	... 24 more
04-11 11:53:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.message.DbException.toSQLException(DbException.java:268)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:352)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:124)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJson(H2ConnectionManager.java:380)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJsonWhereEqual(H2ConnectionManager.java:344)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getForId(InternalDbManager.java:266)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.existsUser(InternalDbManager.java:775)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getUserStatus(InternalDbManager.java:1616)
	at ioc.liturgical.ws.app.ServiceProvider.lambda$0(ServiceProvider.java:324)
	at spark.FilterImpl$1.handle(FilterImpl.java:62)
	at spark.http.matching.BeforeFilters.execute(BeforeFilters.java:48)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcResultSet.nextRow(JdbcResultSet.java:3233)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:122)
	... 24 more
04-11 14:12:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.message.DbException.toSQLException(DbException.java:268)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:352)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:124)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJson(H2ConnectionManager.java:380)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJsonWhereEqual(H2ConnectionManager.java:344)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getForId(InternalDbManager.java:266)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.existsUser(InternalDbManager.java:775)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getUserStatus(InternalDbManager.java:1616)
	at ioc.liturgical.ws.app.ServiceProvider.lambda$0(ServiceProvider.java:324)
	at spark.FilterImpl$1.handle(FilterImpl.java:62)
	at spark.http.matching.BeforeFilters.execute(BeforeFilters.java:48)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcStatement.checkClosed(JdbcStatement.java:986)
	at org.h2.jdbc.JdbcPreparedStatement.checkClosed(JdbcPreparedStatement.java:1620)
	at org.h2.jdbc.JdbcStatement.checkClosed(JdbcStatement.java:959)
	at org.h2.jdbc.JdbcResultSet.checkClosed(JdbcResultSet.java:3177)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:121)
	... 24 more
04-11 14:40:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-187]
04-11 15:53:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.message.DbException.toSQLException(DbException.java:268)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:352)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:124)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJson(H2ConnectionManager.java:380)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJsonWhereEqual(H2ConnectionManager.java:344)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getForId(InternalDbManager.java:266)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.existsUser(InternalDbManager.java:775)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getUserStatus(InternalDbManager.java:1616)
	at ioc.liturgical.ws.app.ServiceProvider.lambda$0(ServiceProvider.java:324)
	at spark.FilterImpl$1.handle(FilterImpl.java:62)
	at spark.http.matching.BeforeFilters.execute(BeforeFilters.java:48)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcResultSet.nextRow(JdbcResultSet.java:3231)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:122)
	... 24 more
04-11 16:24:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.message.DbException.toSQLException(DbException.java:268)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:352)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:124)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJson(H2ConnectionManager.java:380)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJsonWhereEqual(H2ConnectionManager.java:344)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getForId(InternalDbManager.java:266)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.existsUser(InternalDbManager.java:775)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getUserStatus(InternalDbManager.java:1616)
	at ioc.liturgical.ws.app.ServiceProvider.lambda$0(ServiceProvider.java:324)
	at spark.FilterImpl$1.handle(FilterImpl.java:62)
	at spark.http.matching.BeforeFilters.execute(BeforeFilters.java:48)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcResultSet.nextRow(JdbcResultSet.java:3231)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:122)
	... 24 more
04-11 16:33:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.message.DbException.toSQLException(DbException.java:268)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:352)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:124)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJson(H2ConnectionManager.java:380)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJsonWhereEqual(H2ConnectionManager.java:344)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getForId(InternalDbManager.java:266)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.existsUser(InternalDbManager.java:775)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getUserStatus(InternalDbManager.java:1616)
	at ioc.liturgical.ws.app.ServiceProvider.lambda$0(ServiceProvider.java:324)
	at spark.FilterImpl$1.handle(FilterImpl.java:62)
	at spark.http.matching.BeforeFilters.execute(BeforeFilters.java:48)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcResultSet.nextRow(JdbcResultSet.java:3233)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:122)
	... 24 more
04-12 11:04:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.message.DbException.toSQLException(DbException.java:268)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:352)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:124)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJson(H2ConnectionManager.java:380)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJsonWhereEqual(H2ConnectionManager.java:344)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getForId(InternalDbManager.java:266)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.existsUser(InternalDbManager.java:775)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getUserStatus(InternalDbManager.java:1616)
	at ioc.liturgical.ws.app.ServiceProvider.lambda$0(ServiceProvider.java:324)
	at spark.FilterImpl$1.handle(FilterImpl.java:62)
	at spark.http.matching.BeforeFilters.execute(BeforeFilters.java:48)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcResultSet.nextRow(JdbcResultSet.java:3231)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:122)
	... 24 more
04-12 11:14:44 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-187]
04-12 12:15:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.message.DbException.toSQLException(DbException.java:268)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:352)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:124)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJson(H2ConnectionManager.java:380)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJsonWhereEqual(H2ConnectionManager.java:344)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getForId(InternalDbManager.java:266)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.existsUser(InternalDbManager.java:775)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getUserStatus(InternalDbManager.java:1616)
	at ioc.liturgical.ws.app.ServiceProvider.lambda$0(ServiceProvider.java:324)
	at spark.FilterImpl$1.handle(FilterImpl.java:62)
	at spark.http.matching.BeforeFilters.execute(BeforeFilters.java:48)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcResultSet.nextRow(JdbcResultSet.java:3233)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:122)
	... 24 more
04-12 12:39:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-187]
04-12 12:48:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.message.DbException.toSQLException(DbException.java:268)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:352)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:124)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJson(H2ConnectionManager.java:380)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJsonWhereEqual(H2ConnectionManager.java:344)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getForId(InternalDbManager.java:266)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.existsUser(InternalDbManager.java:775)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getUserStatus(InternalDbManager.java:1616)
	at ioc.liturgical.ws.app.ServiceProvider.lambda$0(ServiceProvider.java:324)
	at spark.FilterImpl$1.handle(FilterImpl.java:62)
	at spark.http.matching.BeforeFilters.execute(BeforeFilters.java:48)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcResultSet.nextRow(JdbcResultSet.java:3231)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:122)
	... 24 more
04-12 14:07:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.message.DbException.toSQLException(DbException.java:268)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:352)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:124)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJson(H2ConnectionManager.java:380)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJsonWhereEqual(H2ConnectionManager.java:344)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getForId(InternalDbManager.java:266)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.existsUser(InternalDbManager.java:775)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getUserStatus(InternalDbManager.java:1616)
	at ioc.liturgical.ws.app.ServiceProvider.lambda$0(ServiceProvider.java:324)
	at spark.FilterImpl$1.handle(FilterImpl.java:62)
	at spark.http.matching.BeforeFilters.execute(BeforeFilters.java:48)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcResultSet.nextRow(JdbcResultSet.java:3233)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:122)
	... 24 more
04-12 16:09:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.message.DbException.toSQLException(DbException.java:268)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:352)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:124)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJson(H2ConnectionManager.java:380)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJsonWhereEqual(H2ConnectionManager.java:344)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getForId(InternalDbManager.java:266)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.existsUser(InternalDbManager.java:775)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getUserStatus(InternalDbManager.java:1616)
	at ioc.liturgical.ws.app.ServiceProvider.lambda$0(ServiceProvider.java:324)
	at spark.FilterImpl$1.handle(FilterImpl.java:62)
	at spark.http.matching.BeforeFilters.execute(BeforeFilters.java:48)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcResultSet.nextRow(JdbcResultSet.java:3231)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:122)
	... 24 more
04-12 16:20:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.message.DbException.toSQLException(DbException.java:268)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:352)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:124)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJson(H2ConnectionManager.java:380)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJsonWhereEqual(H2ConnectionManager.java:344)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getForId(InternalDbManager.java:266)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.existsUser(InternalDbManager.java:775)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getUserStatus(InternalDbManager.java:1616)
	at ioc.liturgical.ws.app.ServiceProvider.lambda$0(ServiceProvider.java:324)
	at spark.FilterImpl$1.handle(FilterImpl.java:62)
	at spark.http.matching.BeforeFilters.execute(BeforeFilters.java:48)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcResultSet.nextRow(JdbcResultSet.java:3231)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:122)
	... 24 more
04-13 09:56:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-187]
04-13 10:00:53 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-187]
04-13 11:34:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-187]
04-13 13:29:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.message.DbException.toSQLException(DbException.java:268)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:352)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:124)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJson(H2ConnectionManager.java:380)
	at net.ages.alwb.utils.core.datastores.db.h2.manager.H2ConnectionManager.queryForJsonWhereEqual(H2ConnectionManager.java:344)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getForId(InternalDbManager.java:266)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.existsUser(InternalDbManager.java:775)
	at ioc.liturgical.ws.managers.databases.internal.InternalDbManager.getUserStatus(InternalDbManager.java:1616)
	at ioc.liturgical.ws.app.ServiceProvider.lambda$0(ServiceProvider.java:324)
	at spark.FilterImpl$1.handle(FilterImpl.java:62)
	at spark.http.matching.BeforeFilters.execute(BeforeFilters.java:48)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.h2.jdbc.JdbcResultSet.nextRow(JdbcResultSet.java:3231)
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:122)
	... 24 more
